FROM alpine AS builder
WORKDIR /aggregator
ARG TARGETPLATFORM
COPY clash /aggregator/clash
COPY subconverter /aggregator/subconverter
COPY subscribe /aggregator/subscribe 
COPY requirements.txt /aggregator
RUN set -ex \
    && rm -rf clash/clash-darwin* clash/clash-windows* subconverter/subconverter-darwin* subconverter/subconverter-windows* \
    && if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    rm -rf clash/clash-linux-arm* subconverter/subconverter-linux-arm*; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    rm -rf clash/clash-linux-amd* subconverter/subconverter-linux-amd*; \
    fi
FROM python:alpine AS dist
WORKDIR /aggregator
ENV GIST_PAT="" \
    GIST_LINK="" \
    CUSTOMIZE_LINK="" \
    ENABLE_SPECIAL_PROTOCOLS="true"
COPY --from=builder /aggregator /aggregator
RUN set -ex \
    && pip install --root-user-action=ignore --no-cache-dir -r requirements.txt
CMD ["python", "-u", "subscribe/collect.py", "--all", "--overwrite", "--skip"]
