name: Build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          path: own

      - name: Git clone repository
        uses: actions/checkout@main
        with:
          repository: wzdnzd/aggregator
          ref: main
          path: aggregator

      - name: Copy files
        run: |
          cd aggregator
          echo "VERSION=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          cp -af ../own/. .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: aggregator
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ===========================================================================

  reset:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Branch
        run: |
          git checkout --orphan tmp_work
          git branch -d main

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          create_branch: true
          branch: main
          push_options: --force
